# Generated by Django 5.2.5 on 2025-09-01 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="author",
        ),
    ]
